"use client";
import React, { useState, useEffect } from "react";
import ProtectedRoute from "@/app/_components/protectedRoute";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import customFetch from "@/lib/fetch";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { Label } from "@/components/ui/label";
import { Search } from "lucide-react";
import { jsPDF } from "jspdf";
import { Download } from "lucide-react";

function HRDashboardPage() {
  const router = useRouter();
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({
    role: "",
    currentStatus: "",
    workingProject: "",
  });
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const timer = setTimeout(() => {
      fetchUsers();
    }, 300); // Debounce for 300ms

    return () => clearTimeout(timer);
  }, [filters, searchQuery]);

  const fetchUsers = async () => {
    try {
      setLoading(true);

      let response;
      if (searchQuery) {
        // Use search endpoint if there's a search query
        response = await customFetch(
          `/users/search?query=${encodeURIComponent(searchQuery)}`
        );
      } else {
        // Use filtered endpoint if no search query
        const queryParams = new URLSearchParams();
        if (filters.role) queryParams.append("role", filters.role);
        if (filters.currentStatus)
          queryParams.append("currentStatus", filters.currentStatus);
        if (filters.workingProject)
          queryParams.append("workingProject", filters.workingProject);
        console.log(queryParams.toString());

        response = await customFetch(
          `/users/filtered-users?${queryParams.toString()}`
        );
      }

      setUsers(response);
    } catch (error) {
      console.error("Error fetching users:", error);
      toast.error("Failed to fetch users", {
        description: error.message || "Please try again later",
      });
    } finally {
      setLoading(false);
    }
  };

  const generateEmployeePDF = (employee) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    const lineHeight = 7;

    // Header
    doc.setFontSize(18).setFont("helvetica", "bold");
    doc.text("Employee Profile", pageWidth / 2, 20, { align: "center" });
    doc.setLineWidth(0.5).line(margin, 25, pageWidth - margin, 25);

    let y = 35;

    const addRow = (label, value) => {
      doc.setFont("helvetica", "bold");
      const labelLines = doc.splitTextToSize(label + ":", 40);
      doc.text(labelLines, margin, y);

      doc.setFont("helvetica", "normal");
      const valueLines = doc.splitTextToSize(value || "N/A", maxWidth - 50);

      const neededHeight =
        Math.max(labelLines.length, valueLines.length) * lineHeight;

      if (y + neededHeight > 270) {
        doc.addPage();
        y = 20;
      }

      doc.text(valueLines, margin + 50, y);
      y += neededHeight + 5;
    };

    // Basic Information
    addRow("Full Name", `${employee.firstname} ${employee.lastname}`);
    addRow("Username", employee.username);
    addRow("Email", employee.email);
    addRow("Role", employee.role);
    addRow("Status", employee.currentStatus);
    addRow("Years of Experience", employee.yearsOfExperience.toString());
    addRow("Salary", `$${employee.salary.toLocaleString()}`);

    // Contact Information
    y += 5;
    doc.setFont("helvetica", "bold").setFontSize(14);
    doc.text("Contact Information", margin, y);
    y += 10;
    doc.setFontSize(12);

    addRow("Phone", employee.phone);
    addRow("Email", employee.email);

    // Footer
    doc.setFontSize(10).setTextColor(150);
    doc.text("Generated by HR System", margin, 285);

    // Save the PDF
    doc.save(`employee-${employee.username}.pdf`);
  };

  const handleFilterChange = (name, value) => {
    const finalValue = value === "all" ? "" : value;
    setFilters((prev) => ({ ...prev, [name]: finalValue }));
  };

  const handleSearchChange = (e) => {
    setSearchQuery(e.target.value);
  };

  const handleViewUser = (userId) => {
    router.push(`/authenticated/hr/employee/${userId}`);
  };

  return (
    <ProtectedRoute roles={["hr"]}>
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold">Employee Management</h1>
          <Link href="/authenticated/hr/addEmployee">
            <Button>Add New Employee</Button>
          </Link>
        </div>

        {/* Search Bar */}
        <div className="relative mb-6">
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search className="h-5 w-5 text-gray-400" />
          </div>
          <Input
            type="text"
            placeholder="Search employees by name, email, or username..."
            className="pl-10"
            value={searchQuery}
            onChange={handleSearchChange}
          />
        </div>

        {/* Filters Section - Only show when not searching */}
        {!searchQuery && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
            <div>
              <Label htmlFor="role">Role</Label>
              <Input
                id="role"
                placeholder="Filter by role"
                value={filters.role}
                onChange={(e) => handleFilterChange("role", e.target.value)}
              />
            </div>

            <div>
              <Label htmlFor="workingProject">Working Project</Label>
              <Input
                id="workingProject"
                placeholder="Filter by project"
                value={filters.workingProject}
                onChange={(e) =>
                  handleFilterChange("workingProject", e.target.value)
                }
              />
            </div>

            <div>
              <Label htmlFor="currentStatus">Current Status</Label>
              <Select
                value={filters.currentStatus || "all"}
                onValueChange={(value) =>
                  handleFilterChange("currentStatus", value)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="working on project">
                    Working on project
                  </SelectItem>
                  <SelectItem value="on bench">On bench</SelectItem>
                  <SelectItem value="chief">Chief</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        )}

        {/* Users Table */}
        <div className="border rounded-lg overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Username</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Role</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Experience</TableHead>
                <TableHead>Salary</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center">
                    <div className="space-y-2">
                      {[...Array(5)].map((_, i) => (
                        <Skeleton key={i} className="h-12 w-full" />
                      ))}
                    </div>
                  </TableCell>
                </TableRow>
              ) : users.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center py-8">
                    {searchQuery
                      ? "No employees found matching your search"
                      : "No employees found matching your filters"}
                  </TableCell>
                </TableRow>
              ) : (
                users.map((user) => (
                  <TableRow key={user._id}>
                    <TableCell>
                      {user.firstname} {user.lastname}
                    </TableCell>
                    <TableCell>{user.username}</TableCell>
                    <TableCell>{user.email}</TableCell>
                    <TableCell>{user.role}</TableCell>
                    <TableCell>
                      <span
                        className={`px-2 py-1 rounded-full text-xs ${
                          user.currentStatus === "working on project"
                            ? "bg-green-100 text-green-800"
                            : user.currentStatus === "on bench"
                            ? "bg-yellow-100 text-yellow-800"
                            : "bg-purple-100 text-purple-800"
                        }`}
                      >
                        {user.currentStatus}
                      </span>
                    </TableCell>
                    <TableCell>{user.yearsOfExperience} years</TableCell>
                    <TableCell>${user.salary.toLocaleString()}</TableCell>
                    <TableCell className={"flex space-x-2"}>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => handleViewUser(user._id)}
                      >
                        View
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => generateEmployeePDF(user)}
                        title="Download PDF"
                      >
                        <Download size={16} />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </ProtectedRoute>
  );
}

export default HRDashboardPage;
